import { Router, type IRouter, type Request, type Response } from "express";
import { execSync } from "child_process";
import { mkdtempSync, writeFileSync, mkdirSync, rmSync, chmodSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";
import { logger } from "../lib/logger";

const router: IRouter = Router();

const PROD_URL = "https://insight-dashboard-meulegale1.replit.app/assistente/";
const PKG     = "br.com.assistente.ia.juridico";
const APP_NAME = "Assistente IA Jurídico";
const GRADLE_VERSION = "8.11.1";
const AGP_VERSION    = "8.2.2";
const KOTLIN_VERSION = "1.9.22";

// ── arquivo gradlew (script shell padrão do Gradle) ─────────────────────────
const GRADLEW = `#!/bin/sh
#
# Copyright 2015 the original author or authors.
# Gradle start-up script for POSIX generated by Gradle 8.x
#
set -e
CURRENT_DIR=\`pwd\`
APP_NAME="Gradle"
APP_BASE_NAME=\`basename "\$0"\`
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
CLASSPATH=\`dirname "\$0"\`/gradle/wrapper/gradle-wrapper.jar
exec "\${JAVA_HOME}/bin/java" \$DEFAULT_JVM_OPTS \$JAVA_OPTS -classpath "\$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "\$@"
`;

const GRADLEW_BAT = `@rem Gradle startup script for Windows
@if "%DEBUG%"=="" @echo off
@rem Set local scope
setlocal
set DIRNAME=%~dp0
set CLASSPATH=%DIRNAME%gradle\\wrapper\\gradle-wrapper.jar
"%JAVA_HOME%\\bin\\java" %DEFAULT_JVM_OPTS% %JAVA_OPTS% -classpath "%CLASSPATH%" org.gradle.wrapper.GradleWrapperMain %*
endlocal
`;

const WRAPPER_PROPS = `distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\\://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
`;

const ROOT_BUILD_GRADLE = `buildscript {
    repositories { google(); mavenCentral() }
    dependencies {
        classpath 'com.android.tools.build:gradle:${AGP_VERSION}'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:${KOTLIN_VERSION}'
    }
}
allprojects { repositories { google(); mavenCentral() } }
task clean(type: Delete) { delete rootProject.buildDir }
`;

const SETTINGS_GRADLE = `rootProject.name = "AssistenteIAJuridico"
include ':app'
`;

const GRADLE_PROPERTIES = `android.useAndroidX=true
android.enableJetifier=true
org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.daemon=false
`;

const APP_BUILD_GRADLE = `plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace '${PKG}'
    compileSdk 34

    defaultConfig {
        applicationId "${PKG}"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        debug  { minifyEnabled false }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
`;

const MANIFEST = `<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/Theme.App"
        android:usesCleartextTraffic="false">

        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:configChanges="orientation|screenSize|keyboardHidden">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

    </application>
</manifest>
`;

const MAIN_ACTIVITY = `package ${PKG}

import android.annotation.SuppressLint
import android.graphics.Color
import android.os.Bundle
import android.webkit.WebChromeClient
import android.webkit.WebSettings
import android.webkit.WebView
import android.webkit.WebViewClient
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {
    private lateinit var webView: WebView

    @SuppressLint("SetJavaScriptEnabled")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        webView = WebView(this).apply {
            setBackgroundColor(Color.parseColor("#0d1520"))
        }
        setContentView(webView)

        webView.settings.apply {
            javaScriptEnabled = true
            domStorageEnabled = true
            databaseEnabled = true
            allowFileAccess = true
            mixedContentMode = WebSettings.MIXED_CONTENT_NEVER_ALLOW
            setSupportZoom(true)
            builtInZoomControls = false
            displayZoomControls = false
            loadWithOverviewMode = true
            useWideViewPort = true
            cacheMode = WebSettings.LOAD_DEFAULT
        }

        webView.webViewClient = WebViewClient()
        webView.webChromeClient = WebChromeClient()

        if (savedInstanceState != null) {
            webView.restoreState(savedInstanceState)
        } else {
            webView.loadUrl("${PROD_URL}")
        }
    }

    override fun onSaveInstanceState(outState: Bundle) {
        super.onSaveInstanceState(outState)
        webView.saveState(outState)
    }

    @Deprecated("Deprecated in Java")
    override fun onBackPressed() {
        if (webView.canGoBack()) webView.goBack() else super.onBackPressed()
    }
}
`;

const STRINGS_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="app_name">${APP_NAME}</string>
</resources>
`;

const THEMES_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <style name="Theme.App" parent="Theme.AppCompat.NoActionBar">
        <item name="colorPrimary">#0d1520</item>
        <item name="colorPrimaryDark">#0d1520</item>
        <item name="colorAccent">#7c3aed</item>
        <item name="android:windowBackground">#0d1520</item>
        <item name="android:statusBarColor">#0d1520</item>
        <item name="android:navigationBarColor">#0d1520</item>
    </style>
</resources>
`;

const PROGUARD = `-keep class ${PKG}.** { *; }
`;

const GITIGNORE = `*.iml
.gradle
/local.properties
/.idea
.DS_Store
/build
/captures
.externalNativeBuild
.cxx
local.properties
# NÃO ignorar gradle-wrapper.jar — necessário para o build funcionar
!gradle/wrapper/gradle-wrapper.jar
`;

const GITHUB_WORKFLOW = `name: Build Android APK
on:
  workflow_dispatch:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verificar gradle-wrapper.jar
        run: |
          if [ ! -f gradle/wrapper/gradle-wrapper.jar ]; then
            echo "ERRO: gradle-wrapper.jar ausente. Adicione !gradle/wrapper/gradle-wrapper.jar no .gitignore"
            exit 1
          fi
          echo "OK: gradle-wrapper.jar presente (\$(du -sh gradle/wrapper/gradle-wrapper.jar | cut -f1))"

      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Licenças + build tools
        run: |
          yes | sdkmanager --licenses 2>/dev/null || true
          sdkmanager "build-tools;34.0.0" "platforms;android-34" 2>/dev/null || true

      - name: Permissão gradlew
        run: chmod +x gradlew

      - name: Build APK
        env:
          GRADLE_OPTS: "-Xmx3g -Dorg.gradle.daemon=false -Dfile.encoding=UTF-8"
        run: ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Publicar Release
        env:
          GITHUB_TOKEN: \${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="apk-\$(date +'%Y%m%d-%H%M')"
          cp app/build/outputs/apk/debug/app-debug.apk assistente-ia-juridico.apk
          gh release delete latest --yes 2>/dev/null || true
          gh release create "\$TAG" assistente-ia-juridico.apk \\
            --title "Assistente IA Jurídico — APK" \\
            --notes "Build automático. Baixe e instale o .apk no celular." \\
            --latest
`;

// ── Endpoint principal ────────────────────────────────────────────────────────
router.post("/android-zip", async (req: Request, res: Response) => {
  const tmpDir = mkdtempSync(join(tmpdir(), "android-zip-"));

  try {
    logger.info("android-zip: gerando projeto WebView Android");

    // ── Baixa gradle-wrapper.jar do GitHub oficial ───────────────────────────
    const jarUrl = `https://github.com/gradle/gradle/raw/refs/tags/v${GRADLE_VERSION}/gradle/wrapper/gradle-wrapper.jar`;
    logger.info({ jarUrl }, "android-zip: baixando gradle-wrapper.jar");

    const jarRes = await fetch(jarUrl, {
      signal: AbortSignal.timeout(30_000),
      headers: { "User-Agent": "AssistenteIA-Build/1.0" },
    });

    if (!jarRes.ok) {
      throw new Error(`Falha ao baixar gradle-wrapper.jar: ${jarRes.status} ${jarRes.statusText}`);
    }

    const jarBytes = Buffer.from(await jarRes.arrayBuffer());
    logger.info({ bytes: jarBytes.length }, "android-zip: gradle-wrapper.jar baixado");

    // ── Baixa ícone da produção ──────────────────────────────────────────────
    let iconBytes: Buffer | null = null;
    try {
      const iconRes = await fetch(`${PROD_URL}icon-192.png`, {
        signal: AbortSignal.timeout(10_000),
      });
      if (iconRes.ok) {
        iconBytes = Buffer.from(await iconRes.arrayBuffer());
        logger.info({ bytes: iconBytes.length }, "android-zip: ícone baixado");
      }
    } catch {
      logger.warn("android-zip: falha ao baixar ícone — usando placeholder");
    }

    // ── Cria estrutura de pastas ─────────────────────────────────────────────
    const dirs = [
      "gradle/wrapper",
      ".github/workflows",
      "app/src/main/kotlin/br/com/assistente/ia/juridico",
      "app/src/main/res/values",
      "app/src/main/res/mipmap-mdpi",
      "app/src/main/res/mipmap-hdpi",
      "app/src/main/res/mipmap-xhdpi",
      "app/src/main/res/mipmap-xxhdpi",
      "app/src/main/res/mipmap-xxxhdpi",
    ];
    for (const d of dirs) mkdirSync(join(tmpDir, d), { recursive: true });

    // ── Escreve todos os arquivos ────────────────────────────────────────────
    const files: [string, string | Buffer][] = [
      ["gradlew",                                                    GRADLEW],
      ["gradlew.bat",                                                GRADLEW_BAT],
      ["gradle/wrapper/gradle-wrapper.properties",                   WRAPPER_PROPS],
      ["build.gradle",                                               ROOT_BUILD_GRADLE],
      ["settings.gradle",                                            SETTINGS_GRADLE],
      ["gradle.properties",                                          GRADLE_PROPERTIES],
      [".gitignore",                                                  GITIGNORE],
      [".github/workflows/build-apk.yml",                            GITHUB_WORKFLOW],
      ["app/build.gradle",                                           APP_BUILD_GRADLE],
      ["app/proguard-rules.pro",                                     PROGUARD],
      ["app/src/main/AndroidManifest.xml",                           MANIFEST],
      ["app/src/main/kotlin/br/com/assistente/ia/juridico/MainActivity.kt", MAIN_ACTIVITY],
      ["app/src/main/res/values/strings.xml",                        STRINGS_XML],
      ["app/src/main/res/values/themes.xml",                         THEMES_XML],
    ];

    for (const [path, content] of files) {
      writeFileSync(join(tmpDir, path), content);
    }

    // gradle-wrapper.jar (binário)
    writeFileSync(join(tmpDir, "gradle/wrapper/gradle-wrapper.jar"), jarBytes);

    // ícone em todas as densidades
    if (iconBytes) {
      for (const density of ["mipmap-mdpi", "mipmap-hdpi", "mipmap-xhdpi", "mipmap-xxhdpi", "mipmap-xxxhdpi"]) {
        writeFileSync(join(tmpDir, `app/src/main/res/${density}/ic_launcher.png`), iconBytes);
        writeFileSync(join(tmpDir, `app/src/main/res/${density}/ic_launcher_round.png`), iconBytes);
      }
    }

    // gradlew precisa ser executável
    chmodSync(join(tmpDir, "gradlew"), 0o755);

    // ── Gera ZIP via Python (zip CLI não disponível no ambiente) ─────────────
    const zipPath = join(tmpdir(), `assistente-ia-android-${Date.now()}.zip`);
    const pyScriptPath = join(tmpdir(), `makez-${Date.now()}.py`);

    // Escrevemos o script em arquivo para evitar problemas de escaping no shell
    const pyLines = [
      "import zipfile, os, stat",
      `src = r"""${tmpDir}"""`,
      `dst = r"""${zipPath}"""`,
      "with zipfile.ZipFile(dst, 'w', zipfile.ZIP_DEFLATED) as zf:",
      "    for root, dirs, files in os.walk(src):",
      "        for fname in files:",
      "            full = os.path.join(root, fname)",
      "            arcname = os.path.relpath(full, src)",
      "            info = zipfile.ZipInfo(arcname)",
      "            fstat = os.stat(full)",
      "            if fstat.st_mode & stat.S_IXUSR:",
      "                info.external_attr = (fstat.st_mode | 0o755) << 16",
      "            else:",
      "                info.external_attr = fstat.st_mode << 16",
      "            info.compress_type = zipfile.ZIP_DEFLATED",
      "            with open(full, 'rb') as f:",
      "                zf.writestr(info, f.read())",
      "print('ok')",
    ];

    writeFileSync(pyScriptPath, pyLines.join("\n"));
    execSync(`python3 "${pyScriptPath}"`, { timeout: 30_000 });
    try { rmSync(pyScriptPath, { force: true }); } catch { /* ignore */ }

    logger.info({ zipPath }, "android-zip: ZIP gerado");

    res.setHeader("Content-Type", "application/zip");
    res.setHeader("Content-Disposition", 'attachment; filename="assistente-ia-juridico-android.zip"');
    res.sendFile(zipPath, (err) => {
      try { rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }
      try { rmSync(zipPath, { force: true }); } catch { /* ignore */ }
      if (err) logger.error({ err: String(err) }, "android-zip: erro ao enviar arquivo");
    });

  } catch (e) {
    try { rmSync(tmpDir, { recursive: true, force: true }); } catch { /* ignore */ }
    const msg = e instanceof Error ? e.message : String(e);
    logger.error({ err: msg }, "android-zip: erro");
    if (!res.headersSent) {
      res.status(500).json({ error: `Falha ao gerar ZIP: ${msg}` });
    }
  }
});

export default router;
